name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当主分支有推送时触发
    paths:
      - 'website/**'  # 仅当website目录下的文件发生变化时触发

  # 允许手动触发工作流
  workflow_dispatch:

# 设置GITHUB_TOKEN的权限
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Prepare Website
        run: |
          echo "Preparing website..."
          mkdir -p build
          cp -r website/* build/
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build      # 要部署的文件夹
          branch: gh-pages   # 部署到的分支
          clean: true        # 自动清理旧文件 